In [1]:
import numpy as np

In [16]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [17]:
arr[::-1]

array([4, 3, 2, 1, 0])

In [18]:
np.flip(arr) # 배열을 뒤집어주는 함수

array([4, 3, 2, 1, 0])

In [30]:
arr2d=np.arange(30).reshape(6,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [32]:
np.flip(arr2d) #default 값으로 지정 -> axis 지정안한경우 : 행방향으로 뒤집어 지고 열 방향으로도 역순으로 뒤집어짐

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [35]:
arr2d[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [36]:
arr2d[:,::-1][::-1]

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [37]:
np.flip(arr2d,axis=0)             #axis(축),axes(모든 축) axis=0 (행 방향 뒤집기) axis=1 (열 방향 뒤집기)

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [38]:
arr2d[::-1]

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [39]:
np.flip(arr2d,axis=1)

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [41]:
arr2d[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [47]:
arr1=np.zeros([3,3])
arr2=np.ones([3,2])
arr12=np.hstack([arr1,arr2])

In [48]:
arr3=np.arange(10,151,10).reshape(3,-1)

In [49]:
arr_v=np.vstack([arr12,arr3])
np.vstack([arr_v,arr_v])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [60]:
arr1=np.zeros([3])
arr2=np.ones([2])
arr12=np.hstack([arr1,arr2])
arr12

array([0., 0., 0., 1., 1.])

In [61]:
arr12tile=np.tile(arr12,(3,1)) #arr12를 반복해라 행으로 3번 좌우로 1번

In [62]:
arr123=np.linspace(10,150,15).reshape(3,-1) #10 부터 150까지 균등한 간격으로 15개 생성
arr123

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [63]:
arr123=np.vstack([arr12tile,arr123])
arr123

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [64]:
np.tile(arr123,(2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [65]:
arr=np.arange(10,15)

In [66]:
np.sum(arr) #합계

60

In [67]:
arr.sum() #합계 함수 다른 방법

60

In [69]:
np.min(arr) # 최소값
np.max(arr) # 최대값

14

In [70]:
arr.min() # 이 문법도 가능
arr.max()

14

In [72]:
arr=np.arange(11,21).reshape(2,-1)

In [74]:
np.sum(arr)
arr.sum()

155

In [75]:
np.min(arr)
arr.min()
np.max(arr)
arr.max()

20

In [80]:
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [79]:

arr.argmin() #최소값이 저장되어있는 인덱스 번호 추출

0

In [77]:
arr.argmax() #최대값이 저장되어있는 인덱스 번호 추출 2차원 구조에서도 처음 0부터 쭉 셈

9

In [81]:
arr[0].argmin() #0 각각의 행에 대해서 함수 사용하면 행 내에서의 최댓값과 최솟값 인덱스 추출
arr[0].argmax() #4

4

In [82]:
arr.mean() #전체 요소값에 대한 평균

15.5

In [83]:
arr[0].mean() #0번 행에 대한 요소의 평균값

13.0

In [85]:
np.mean(arr) #도 가능

15.5

In [86]:
#산술평균 -> n을 다 더한후 n개로 나눈 값 ->극단값에 영향을 많이 받음 ex 1000만 2000만 100억 셋의 평균임금은 33억이 넘어감 
# arr.median()이 문법은 사용 불가
np.median(arr) #데이터의 중위값 (가운데 값) 데이터 개수가 홀수일 경우 가운데 중위수가 추출 되지만 데이터 개수가 짝수이면 가운데 2개의 값의 산술평균으로 함

15.5

In [87]:
np.median(arr[0])

13.0

In [88]:
np.all # 모두 다 True(참)인가? 맞으면 True 아니면 False 출력
np.all(2>1)

True

In [89]:
np.all([2>1,5>3, 3<1]) # 두개 이상일시 리스트형식으로 묶어줘야함 하나라도 false가 있으면 false 출력

False

In [90]:
np.any([True,True,False]) #하나라도 True가 있으면 True 출력

True

In [92]:
np.all([1,2,0]) # 0은 False 0이 아니면 참


False

In [94]:
np.all([1,2])

True

In [95]:
np.all(np.arange(5)) #False가 나오는 이유 -> 0이 하나 포함되어 있기때문에 all함수에서는 False가 출력

False

In [96]:
np.all(np.arange(1,5)) #0을 빼면 참으로 출력

True

In [97]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [98]:
np.all((a <= b) & (b <= c)) 

True

In [102]:
arr=np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [103]:
#2차원 이상 다차원 배열에 대한 연산시에는 axis를 지정할 수 있음
#axis=0 (기본값,열방향 연산), axis=1 (행방향 연산)


In [104]:
arr.sum(axis=0) #열방향 연산 위아래로 연산해서 나열

array([ 5,  7,  9, 11, 13])

In [105]:
arr.sum(axis=1)  #행방향 연산 좌우로 연산

array([10, 35])

In [106]:
arr.max(axis=0)

array([5, 6, 7, 8, 9])

In [107]:
arr.max(axis=1)

array([4, 9])

In [131]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])

In [109]:
np.max(a,axis=1)

array([ 7, 12, 15])

In [116]:
a.sort() #정렬 axis=0 (기본값,열방향 연산)
a

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

In [130]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a.sort(axis=0) #위에서 아래로 열마다 오름차순 정렬
a


array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [132]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a.sort(axis=1) #행마다 오름차순 정렬
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [ ]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
np.sort(a)
#기본 default값이 axis=1

In [141]:
#a.sort() 를 하게되면 a 배열이 바뀌지만 np.sort(a)를 하고 a를 출력하면 a배열이 바뀌진 않음
arr=np.array([10,20,30,40,90])

In [142]:
arr2=np.sort(arr)[::-1] #내림차순 정렬 np.sort()를 할 경우에 arr 자체가 변하지는 않음
arr2

array([90, 40, 30, 20, 10])

In [143]:
arr

array([10, 20, 30, 40, 90])

In [145]:
arr=np.array([40,20,10,30,90])
arr

array([40, 20, 10, 30, 90])

In [146]:
arr #정렬 결과를 반영하지 않음

array([40, 20, 10, 30, 90])

In [148]:
arr.sort() #정렬결과 반영
arr

array([10, 20, 30, 40, 90])

In [149]:
len(arr)

5

In [150]:
np.mean(arr)

38.0

In [151]:
np.var(arr) #분산 변수의 흩어진 정도를 계산하는 지표(variance) 
#분산의 제곱근 = 표준편차 , 분산= 각 데이터값에서 데이터의 평균값을 뺀 것의 제곱을 다 합하고 데이터 개수로 나눈 값
#기하학적으로 생각해보면 평균과 각각의 데이터 사이의 평균면적임 왜 why? 평균과 데이터를 뺀것의 제곱  즉 밑변을 두번 곱하므로 정사각형의 면적이 되는것이고 이것을 다 더한것을 데이터의 개수로 나누기 떄문
#결국 데이터값에서 평균값까지의 밑변을 가지는 정사각형의 면적 평균

776.0

In [152]:
np.std(arr) #표준편차= 분산의 제곱근

27.85677655436824

In [153]:
arr

array([10, 20, 30, 40, 90])

In [155]:
x=np.array([5,10,9,3,8])
x

array([ 5, 10,  9,  3,  8])

In [ ]:
x에 대한 표본분산을 구하시오 #모집단에 있는 표본들의 분산

In [157]:
x.var() #-> 모분산

6.8

In [174]:
np.sum(((x-x.mean())**2))/(len(x)-1) #표본분산

8.5

In [194]:
x=np.arange(1,201)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [190]:
np.percentile(x,0) #최소값

1.0

In [191]:
np.percentile(x,100) #백분위수: 위치를 100으로 나눈 수 
# 1사분위수 : 25%에 해당하는 백분위수

201.0

In [192]:
np.percentile(x,25) # 1사분위수 ->데이터에서 25% 위치에 해당하는 값

51.0

In [193]:
np.percentile(x,50) #2사분위 수 ->데이터에서 50%위치에 해당하는값 

101.0

In [195]:
np.percentile(x,75) # 3사분위 수


150.25

In [196]:
np.percentile(x,100) #백분위 수

200.0

In [197]:
data=np.arange(11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [198]:
np.percentile(data,50) # 데이터가 홀수개 이므로 정확히 가운데있는 5가 출력 (중위수= 2사분위수)

5.0

In [199]:
np.percentile(data,25)# 1사분위 수

2.5

In [200]:
np.percentile(data,75) #3사분위 수

7.5

In [201]:
np.percentile(data,100) #백분위 수=4사분위 수

10.0

In [210]:
x=np.arange(1,31).reshape(5,6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [205]:
np.max(x)


30

In [207]:
np.max(x,axis=1)

array([ 6, 12, 18, 24, 30])

In [209]:
np.sum(x,axis=1)

array([ 21,  57,  93, 129, 165])

In [211]:
np.mean(x,axis=0)

array([13., 14., 15., 16., 17., 18.])

In [212]:
np.min(x,axis=1)

array([ 1,  7, 13, 19, 25])

In [219]:
arr=np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
arr

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [237]:
score = np.array([[  1,    2,    3,    4],
                  [ 46,   99,  100,   71],
                  [ 81,   59,   90,  100]])

# 영어 점수로 정렬된 인덱스 가져오기
eng_sorted_indices = np.argsort(score[1])
eng_sorted_indices
# 영어 점수로 정렬된 배열 생성
sorted_score = score[:, eng_sorted_indices]

print(sorted_score)

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]
