In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4])

In [5]:
arr.dtype #정수 데이터이며 이 정수데이터를 저장하는데 32비트(4바이트)가 소요됨
# 1MB=100만 바이트
# 1GB=10억 바이트

dtype('int32')

In [6]:
type(arr) #arr의 타입은 n차원의 array ndarray가 나옴->arr안에 있는 배열 데이터가 정수

numpy.ndarray

In [8]:
type(arr[0])

numpy.int32

In [9]:
arr=np.array(['Apple','CHERRY','BANANA'])
arr.dtype # <U6 : unicode

dtype('<U6')

In [11]:
arr=np.array([1,2,3], dtype=np.float64) #64비트 float 수의 범위 4.9*10의 -324승~ 1.17 *10의 308승
arr.dtype

dtype('float64')

In [16]:
arr=np.array([1,2,3], dtype='i1') # i= 바이트 수 i1= 1바이트 =int8
arr

array([1, 2, 3], dtype=int8)

In [17]:
arr=np.array([1,2,3])
arr.dtype

dtype('int32')

In [18]:
farr=arr.astype(np.float32) # 타입변환 함수
farr

array([1., 2., 3.], dtype=float32)

In [19]:
arr

array([1, 2, 3])

In [20]:
farr

array([1., 2., 3.], dtype=float32)

In [21]:
arr1=np.array(list(range(10,14))).reshape(2,2)
arr2=np.array(list(range(10,14))).reshape(2,2) #넘파이 배열은 요소간 연산=>동일한 크기의 배열
arr1-arr2


array([[0, 0],
       [0, 0]])

In [22]:
arr1*2 #숫자와 연산을 할때는 모든항목에 동일한 연산

array([[20, 22],
       [24, 26]])

In [23]:
arr1*arr2 #주의 : 행렬의 곱셈(matrix multiply)이 아님, 요소간 곱셈(element-wise product)

array([[100, 121],
       [144, 169]])

#행렬의 곱셈은 도트기호로 나타냄 앞쪽의 행렬의 열과 뒷쪽의 행렬의 행이 같아야함 a*b . b*c= b자리가 같아야하고 나오는 shape는 a행c열 a*c가 됨

In [27]:
import numpy as np
arr1=np.array(list(range(10,14))).reshape(2,2)
arr1

array([[10, 11],
       [12, 13]])

In [29]:
arr2=np.array(list(range(13,17))).reshape(2,2)
arr2

array([[13, 14],
       [15, 16]])

In [30]:
arr1>arr2 #비교연산도 요소간 연산이 이루어짐

array([[False, False],
       [False, False]])

In [31]:
arr1>10

array([[False,  True],
       [ True,  True]])

In [32]:
arr1==arr2

array([[False, False],
       [False, False]])

In [33]:
~(arr1==arr2) #~는 not 연산자

array([[ True,  True],
       [ True,  True]])

In [35]:
arr1!=arr2 # 같지않다 

array([[ True,  True],
       [ True,  True]])

In [36]:
(~(arr1==arr2))|(~(arr1!=arr2))
#|은 or  행렬 OR 행렬 => 요소간 or 연산
# 둘중 하나 이상이 TRUE => TRUE

array([[ True,  True],
       [ True,  True]])

In [37]:
np.arange(8)#np.array(list(range(8)))

array([0, 1, 2, 3, 4, 5, 6, 7])

In [38]:
np.arange(8).reshape(2,2,2) #깊이가 2 행 2 열 2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [42]:
arr1=np.array(list(range(1,25))).reshape(2,3,4)
arr2=np.arange(1,25).reshape(2,3,4)
print(arr1,arr2, sep='\n')

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [43]:
data=np.arange(200)
data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [46]:
data2=data.reshape(4,-1) (4행으로 설정하고 뒤에 -1자리에는 계산해서 생성해줌)
data2

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
         76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
     

In [47]:
data2.shape

(4, 50)

In [48]:
data3=data.reshape(6,-1) #에러가 뜸 200이 6행으로 나누어떨어지지 않기때문

ValueError: cannot reshape array of size 200 into shape (6,newaxis)

In [50]:
data4=data.reshape(-1,10)
data4

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [53]:
data4.shape

(20, 10)

In [55]:
data.reshape(-1,5,10).shape

(4, 5, 10)

In [62]:
np.array(list(range(10,34,2))).reshape(3,4)

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [81]:
#불린참조(팬시)

arr=np.array([1,2,3,4])
idx=np.array([True,False,False,True])

In [82]:
arr[idx] # 각 요소에서 True에 대응되는 값을 출력

array([1, 4])

In [83]:
np.min(arr) #최소값
np.max(arr) #최대값

4

In [84]:
arr

array([1, 2, 3, 4])

In [85]:
arr==1

array([ True, False, False, False])

In [86]:
arr==np.min(arr)
# 1

array([ True, False, False, False])

In [87]:
arr==np.max(arr)
# 4

array([False, False, False,  True])

In [90]:
arr[(arr==np.max(arr))|(arr==np.min(arr))]

array([1, 4])

In [91]:
arr[arr==np.max(arr)]

array([4])

In [96]:
arr[arr==np.array([ True, False, False, False])]

array([1])

In [98]:
arr=np.arange(11,21)

In [99]:
arr %2 #나머지 연산자

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [100]:
arr%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [101]:
arr[arr%2==0]

array([12, 14, 16, 18, 20])

In [102]:
arr[1,3] #error

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [103]:
arr[np.array([1,3])]

array([12, 14])

In [111]:
arr[np.array([1,3])]

array([12, 14])

In [113]:
#arr=array([11,12,13,14,15...20])
idx=np.array([0,0,0,1,1,1,3,3,3])
arr[idx]

array([11, 11, 11, 12, 12, 12, 14, 14, 14])

In [116]:
arr=np.arange(10,40).reshape(5,-1)

In [117]:
arr[:] #전체행 추출
arr[:,:] #전체행에 대해 전체열을 추출
arr[:,[True,True,True,False,False,True]]

array([[10, 11, 12, 15],
       [16, 17, 18, 21],
       [22, 23, 24, 27],
       [28, 29, 30, 33],
       [34, 35, 36, 39]])

In [118]:
idx=np.array([True,True,True,False,False,True])
arr[:,idx]

array([[10, 11, 12, 15],
       [16, 17, 18, 21],
       [22, 23, 24, 27],
       [28, 29, 30, 33],
       [34, 35, 36, 39]])

In [119]:
arr[:,[True,False,True,False,True,False]]

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [123]:

idx=np.array([0,2,4])
arr[:,idx]

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [124]:
arr[:,[4,1,3,0]]

array([[14, 11, 13, 10],
       [20, 17, 19, 16],
       [26, 23, 25, 22],
       [32, 29, 31, 28],
       [38, 35, 37, 34]])

In [125]:
arr[[2,1,3],:]

array([[22, 23, 24, 25, 26, 27],
       [16, 17, 18, 19, 20, 21],
       [28, 29, 30, 31, 32, 33]])

In [126]:
# 무한대(infinity):np.inf
# 숫자 아님 (not a number) :np.nan
np.array([1])/np.array([0]) # 값이 무한대로 나옴
np.array([0])/np.array([0])

C:\Users\master\AppData\Local\Temp\ipykernel_24404\2514585905.py:3: RuntimeWarning: divide by zero encountered in divide
  np.array([1])/np.array([0]) # 값이 무한대로 나옴
C:\Users\master\AppData\Local\Temp\ipykernel_24404\2514585905.py:4: RuntimeWarning: invalid value encountered in divide
  np.array([0])/np.array([0])


array([nan])

In [127]:
np.zeros(3)

array([0., 0., 0.])

In [129]:
np.zeros((3,2)).dtype

dtype('float64')

In [133]:
np.zeros((3,2),dtype='i4')

array([[0, 0],
       [0, 0],
       [0, 0]])

In [134]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [135]:
np.ones((3,2))*2

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [136]:
np.ones_like(arr) # 1로 초기화 하면서 구조를 동일하게

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [138]:
np.arange(2,31,2).reshape(-1,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]])

In [140]:
np.linspace(0,10,5) # 0부터 10까지를 5구간으로 나눠줌

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [145]:
arr=np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
# transpose: 전치행렬(행과열을 바꾼 행렬)
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [148]:
arr.transpose().transpose()

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
arr.T #transpose() 함수와 같은 역할 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [150]:
arr.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
#(사과,배,딸기)
data=np.array([[1,5,0], 
          [5,3,2],
          [1,2,0]]) #3행3열
price=np.array([[1000],
                [5000],
                [8000]]) #3행 1열

In [155]:
#data배열과 price 배열간 행렬의 곱셈 연산 -> 각 날짜별 매출액 계산가능
data.dot(price)  #내적 -> 2차원에서는 행렬의 곱셈과 결과가 같음

array([[26000],
       [36000],
       [11000]])

In [156]:
data@price #행렬의 곱셈

array([[26000],
       [36000],
       [11000]])

In [157]:
arr=np.arange(10,14)
arr

array([10, 11, 12, 13])

In [158]:
arr2=arr #데이터를 공유한다는 의미 (뷰) arr2와 arr데이터가 같은 데이터를 의미 arr2[1]을 바꾸면 둘다 바뀜

In [160]:
arr2[1]=99

In [161]:
arr2

array([10, 99, 12, 13])

In [162]:
arr

array([10, 99, 12, 13])

In [163]:
arr3=arr.copy() #copy함수는 데이터를 복사해서 넣어줌. 하나가 바뀌어도 공유 x
arr3[1]=98

In [164]:
arr3

array([10, 98, 12, 13])

In [165]:
arr2

array([10, 99, 12, 13])

In [166]:
arr

array([10, 99, 12, 13])

In [167]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [169]:
np.arange(10,90,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [172]:
np.arange(1,25).reshape(-1,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [173]:
vector=np.array(range(0,30,2))

In [197]:
vector[vector==24][0]
#vector[-3]

24

In [177]:
vector[vector==6]

array([6])

In [182]:
matrix=np.array(list(range(1,17))).reshape(4,4)

In [183]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [185]:
matrix[1,3]

8

In [186]:
matrix[matrix==8]

array([8])

In [190]:
matrix[0,1]

2

In [191]:
matrix[2,0]

9

In [193]:
matrix[3,2]

15

In [199]:
np.arange(-1,-6,-1)

array([-1, -2, -3, -4, -5])

In [200]:
x=np.arange(1,21)

In [201]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [202]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [210]:
a=x[x%3==0]
a[a%4==1]

array([9])

In [215]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])