In [ ]:
#파이썬 리스트
li=[1,'가',True,[1,2],{'a':1}]
li

[1, '가', True, [1, 2], {'a': 1}]

In [ ]:
"""
넘파이(배열)과 파이썬(리스트) 차이점
배열:모든 자료형이 동일,데이터의 개수를 변경할 수 없다.
파이썬에서 배열을 기본적으로 제공하지 않으므로, 별도로 넘파이 패키지를 설치하여 배열을 사용 데이터 처리를해줌
pandas 데이터 분석을 도와줌
matplotlib 데이터 시각화
pytorch,tensorflow 머신러닝 프레임워크는 아나콘다는 설치해야함 코랩은 깔려있음
"""

'\n넘파이(배열)과 파이썬(리스트) 차이점\n배열:모든 자료형이 동일,데이터의 개수를 변경할 수 없다.\n파이썬에서 배열을 기본적으로 제공하지 않으므로, 별도로 넘파이 패키지를 설치하여 배열을 사용 데이터 처리를해줌 \npandas 데이터 분석을 도와줌\nmatplotlib 데이터 시각화\npytorch,tensorflow 머신러닝 프레임워크는 설치해야함\n'

In [ ]:
pip list

In [ ]:
"""
numpy ->수치연산작업을 빠르게 수행해주는 도구
다차원 배열 구조를 제공 nd array(ndimension array n차원 배열)
벡터와 행렬을 사용하는 선형대수 연산에 사용되는 자료구조

벡터: 숫자를 원소로 갖는 리스트(배열),행벡터,열벡터
행벡터 : x=[x1 x2...xn]
공간에서의 한 점, 원점으로부터 떨어진 상대적 위치 -> 벡터

행렬: 벡터를 원소로 갖는 2차원 배열
공간에서의 여러 점(데이터 모임)
행렬 곱셈을 통해 벡터를 다른 차원의 공간으로 이동할 수 있음.

"""


'\nnumpy ->수치연산작업을 빠르게 수행해주는 도구\n다차원 배열 구조를 제공 nd array(ndimension array n차원 배열)\n벡터와 행렬을 사용하는 선형대수 연산에 사용되는 자료구조\n'

In [ ]:
x=[10,20,30] #x에 저장된 자료타입 list
type(x)

list

In [ ]:
import numpy as np

In [ ]:
array_x=np.array(x) #3차원 벡터의 1차원배열
array_x # x의 타입을 배열로 바꿈
type(array_x) #(ndarray = n차원 배열)

numpy.ndarray

In [ ]:
사과:1000 딸기 : 2000  배:2000 파인애플 : 5000, 바나나:3000
5/1 사과:5 딸기 :2 배:0 파인애플:0 바나나:3
5/2 사과:1 딸기 :3 배:2 파인애플:3 바나나 :2

5차원벡터 : 5차원 공간(사과축 딸기축 등등)에 표현된 한 점

[[5 2 0 0 3] -> 5차원 공간에서의 (5,2,0,0,3 =5콤마 2 콤마 0콤마0콤마 3) 위치를 가진 점. 요소들은 각 차원의 값을 나타냄
[1 3 2 3 2] -> 각각이 행벡터  1 3 2 3 2
            -> [5 1 . . .]이게 열벡터
[...      ]  ->  [2 3 . . .] 이게 열벡터
[...      ]]

덧셈,뺄셈
[5 2 0 0 3]+[1 3 2 3 2] =[6 5 2 3 5] -> 5/1 부터 5 /2 까지 팔린 과일들 각각의 개수

In [20]:
import time
s=time.time()
data=list(range(1,1000000))
ans=[]
#data
for d in data:
    ans.append(d*2)

ans
e=time.time()
print(e-s)

0.535529375076294


In [21]:
arr_data=np.array(data)
arr_data

array([     1,      2,      3, ..., 999997, 999998, 999999])

In [22]:
import time #array에서는 곱 연산을 하면 각각의 요소에대해 한번에 연산 시행 -> 벡터화 연산
s=time.time()
ans2=2*arr_data
e=time.time()
print(e-s)

0.009044408798217773


In [23]:
[1,2,3]*2 #파이썬은 리스트 요소를 두번 출력

[1, 2, 3, 1, 2, 3]

In [26]:
x=[1,2] #python 에서의 연산
y=[3,4]
x+y

[1, 2, 3, 4]

In [27]:
x=np.array(x)
y=np.array(y)
x+y #요소간 덧셈 같은 성분끼리 덧셈

array([4, 6])

In [43]:
#1~100까지 수 중에서 짝수를 even, 홀수를 odd에 저장한 다음, 같은 위치의 요소끼리 비교하여 큰 값을 출력하시오
even=[]
odd=[]

for i in range(1,101):

    if i%2==0:
        even.append(i)
    else:
        odd.append(i)
res=[]
for x in range(0,50):
    if even[x]>odd[x]:
        res.append(even[x])
    else:
        res.append(odd[x])
print(res)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [42]:
even=[]
odd=[]

for i in range(1,101):

    if i%2==0:
        even.append(i)
    else:
        odd.append(i)
a_even=np.array(even)
a_odd=np.array(odd)


In [35]:
a_even+a_odd

array([  3,   7,  11,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51,
        55,  59,  63,  67,  71,  75,  79,  83,  87,  91,  95,  99, 103,
       107, 111, 115, 119, 123, 127, 131, 135, 139, 143, 147, 151, 155,
       159, 163, 167, 171, 175, 179, 183, 187, 191, 195, 199])

In [44]:
a_even>50
a_even==10
(a_even>30) & (a_even%5==0)
a_even #2,4,.....100
a_odd #1,3,5,,,99
a_even[a_even>a_odd]


array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [45]:
np.__version__

'1.25.2'

In [46]:
np.array((10,20,30))


array([10, 20, 30])

In [50]:
#0차원 배열=스칼라= 배열의 각 요소값
arr=np.array(10)
#1차원 배열 = 0차원 배열을 요소로 갖는 배열
arr=np.array([10,20,30])
arr

array([10, 20, 30])

In [53]:
#2차원 배열=1차원 배열을 요소로 갖는 배열= 행렬
arr=np.array([[10,20,30],[40,50,60]])
arr #2행 3열
len(arr) #행의 개수
len(arr[0]) #열의 개수

3

In [56]:
#3차원 배열=2차원배열을 요소로 갖는 배열
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr
arr.ndim #몇차원 배열인지 알수 있음


2

In [58]:
arr=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]],[[19,20],[21,22],[23,24]]]) #4*3*2인 3차원 배열

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [62]:
#2*3*4 -> 제일 바깥쪽 2개의 요소 안에 3개의 요소 안에 4개의 요소가 있는 3차원 배열
li=[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]

In [63]:
# li+1 리스트의 모든 요소에 1을 더하려면 for 문을 돌려야함 li+1은 에러가 남
np.array(li)+1 # array에서는 +1을 하면 각 요소에 1씩 더해짐

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23, 24, 25]]])

In [66]:
arr=np.array(list(range(1,25)))

In [67]:
arr_re=arr.reshape(2,3,4) #1차원 array의 배열을 2*3*4의 3차원 배열로 바꿔줌
arr_re

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [68]:
arr_re.ndim #3차원 배열

3

In [69]:
arr_re.shape

(2, 3, 4)

In [70]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [71]:
arr[0]

1

In [72]:
arr[-1]

4

In [75]:
arr=np.array(list(range(11,21)))
arr=arr.reshape(2,5)

In [76]:
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [77]:
arr[1][3]

19

In [78]:
arr[1,3]

19

In [79]:
arr[-1]

array([16, 17, 18, 19, 20])

In [80]:
arr[-1][-2]

19

In [82]:
arr=np.array(list(range(1,13))).reshape(2,2,3)

In [83]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
arr[0][1][-1] #array indexing

6

In [85]:
arr[0,1,-1]

6

In [86]:
#arr[시작위치 : 끝위치 :간격(스텝)] #array slicing 스텝을 생략하면 기본값으로 1씩 증가
arr=np.array(list(range(1,8)))

In [92]:
arr[1:5] # 끝 위치는 포함 x (이건 파이썬 리스트도 같음)
arr[3:]
arr[:3]

array([1, 2, 3])

In [94]:
arr[1:-3] #음수로 줘도 그 끝위치는 포함 x

array([2, 3, 4])

In [98]:
arr[1:5:2]

array([2, 4])

In [99]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [100]:
arr[::]

array([1, 2, 3, 4, 5, 6, 7])

In [103]:
arr=np.array(list(range(11,41))).reshape(6,5)
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [102]:
arr[1,1:4]

array([7, 8, 9])

In [105]:
arr[4,3]

34

In [107]:
arr[2,0:3]

array([21, 22, 23])

In [117]:
arr[1:3,1:4] #앞에가 행 뒤에가 열 1~2번까지 행에있는 1~3번까지 열을 추출

array([[17, 18, 19],
       [22, 23, 24]])

In [1]:
pip install -U finance-datareader

   ---------------------------------------- 0.0/46.6 kB ? eta -:--:--
   -------------------------- ------------- 30.7/46.6 kB 660.6 kB/s eta 0:00:01
   ---------------------------------------- 46.6/46.6 kB 577.4 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [10]:
kakao_arr=np.loadtxt("kakao_pre.csv",skiprows=1, dtype=np.float32, delimiter=',')

In [11]:
kakao_arr[:5]

array([[  58000.   ,   58900.   ,   57800.   ,   58300.   ,   58237.387,
        1047114.   ],
       [  57200.   ,   57500.   ,   56000.   ,   57200.   ,   57138.57 ,
        2288474.   ],
       [  57500.   ,   58200.   ,   57100.   ,   57700.   ,   57638.03 ,
        1821528.   ],
       [  57800.   ,   58700.   ,   57300.   ,   57500.   ,   57438.246,
        1412568.   ],
       [  57100.   ,   57300.   ,   56300.   ,   56500.   ,   56439.32 ,
        1364811.   ]], dtype=float32)

In [13]:
kakao_arr[:,2]

array([57800., 56000., 57100., 57300., 56300., 56000., 55600., 56100.,
       56000., 55600., 56800., 57200., 57600., 57600., 56700., 56300.,
       56400., 56400., 56100., 56000., 56000., 57000., 57300., 56300.,
       56300., 56400., 56200., 55300., 53700., 53400., 52000., 51500.,
       50300., 50100., 49550., 48600., 49350., 48500., 48700., 48400.,
       49300., 49900., 48800., 48700., 49750., 49450., 50000., 50200.,
       51700., 51600., 52200., 51400., 50100., 50100., 49750., 49400.,
       48800., 46650., 47500., 49600., 50000., 51800., 52300., 52300.,
       51000., 51200., 51800., 52100., 51900., 50600., 50600., 49850.,
       49150., 48200., 48250., 48400., 48450., 48900., 47600., 47800.,
       48000., 48750., 48100., 47950., 48400., 48850., 48500., 48600.,
       48000., 47900., 48150., 47300., 47450., 48100., 48450., 47800.,
       47050., 45600., 44800., 44650., 43400., 43150., 41600., 40700.,
       40600., 41200., 41900., 42600., 43050., 42400., 42800., 41800.,
      

In [19]:
import numpy as np
arr=np.array(list(range(10,90,10))).reshape(2,4)

In [20]:
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [21]:
m=np.array(list(range(0,15))).reshape(3,5)

In [23]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
m[1,2]

7

In [25]:
m[-1,-1]

14

In [26]:
m[1,1:3]

array([6, 7])

In [27]:
m[1:,2]

array([ 7, 12])

In [28]:
m[0:2,3:]

array([[3, 4],
       [8, 9]])

In [30]:
arr=np.array(list(range(10,50)))

In [31]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [38]:
arr[-1::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [42]:
s=np.loadtxt("samsung.csv",skiprows=1, dtype=np.float32, delimiter=',')

In [43]:
s[-1:-3:-1]

array([[   79000.,    79000.,    77500.,    77700.,    77700., 12165808.],
       [   77600.,    78600.,    77300.,    78000.,    78000., 18900640.]],
      dtype=float32)

In [44]:
s.avg

AttributeError: 'numpy.ndarray' object has no attribute 'avg'

In [53]:
siga=s[:,0]
siga

array([65100., 65600., 66300., 65800., 65500., 64700., 63700., 64100.,
       65800., 65900., 66000., 67800., 68400., 68500., 68100., 69900.,
       69800., 71300., 72400., 70900., 71700., 72700., 71300., 70400.,
       71100., 72100., 71700., 72100., 72100., 71800., 71300., 70700.,
       70700., 70200., 72000., 71700., 72500., 72600., 73100., 72500.,
       72700., 73400., 73000., 71900., 71100., 70000., 70200., 71200.,
       72400., 72500., 73200., 73200., 72700., 71100., 70400., 70100.,
       70000., 69800., 69900., 71800., 70900., 70100., 70700., 69900.,
       68800., 67700., 69000., 68000., 68300., 68400., 67500., 66700.,
       66300., 66000., 66600., 67200., 66700., 68300., 67100., 66800.,
       66900., 67300., 67100., 66800., 72900., 70900., 70700., 70000.,
       70200., 70400., 70800., 71100., 71200., 71700., 71300., 70400.,
       70000., 69200., 68300., 68500., 70000., 68600., 67400., 67300.,
       67100., 66200., 68600., 68600., 68000., 67900., 67700., 68900.,
      

In [48]:
jongga=s[:,2]

In [49]:
jongga

array([64900., 64700., 65400., 65100., 64300., 64200., 63600., 63900.,
       65300., 64800., 65700., 67500., 68000., 68100., 68000., 68700.,
       69500., 71200., 71000., 70600., 71600., 71400., 70800., 70000.,
       70800., 70800., 71600., 71100., 71300., 70900., 70900., 70400.,
       70400., 70100., 71600., 71500., 72000., 72000., 72400., 71700.,
       72600., 72900., 71900., 71500., 69800., 69200., 70100., 71100.,
       71900., 72400., 72800., 72000., 71300., 70800., 69400., 69900.,
       69800., 68100., 69300., 70100., 69800., 70000., 69800., 68500.,
       68200., 67600., 67400., 67900., 67800., 67500., 66900., 66300.,
       66000., 65800., 66300., 66300., 66400., 67900., 66900., 66500.,
       66600., 67100., 66400., 66700., 70700., 70200., 69700., 69600.,
       69600., 70000., 70400., 70300., 70800., 71400., 70200., 69600.,
       69500., 68800., 68300., 68500., 68400., 68200., 66700., 66700.,
       66000., 66200., 67900., 68200., 67700., 66800., 67400., 68800.,
      

In [50]:
siga+jongga

array([130000., 130300., 131700., 130900., 129800., 128900., 127300.,
       128000., 131100., 130700., 131700., 135300., 136400., 136600.,
       136100., 138600., 139300., 142500., 143400., 141500., 143300.,
       144100., 142100., 140400., 141900., 142900., 143300., 143200.,
       143400., 142700., 142200., 141100., 141100., 140300., 143600.,
       143200., 144500., 144600., 145500., 144200., 145300., 146300.,
       144900., 143400., 140900., 139200., 140300., 142300., 144300.,
       144900., 146000., 145200., 144000., 141900., 139800., 140000.,
       139800., 137900., 139200., 141900., 140700., 140100., 140500.,
       138400., 137000., 135300., 136400., 135900., 136100., 135900.,
       134400., 133000., 132300., 131800., 132900., 133500., 133100.,
       136200., 134000., 133300., 133500., 134400., 133500., 133500.,
       143600., 141100., 140400., 139600., 139800., 140400., 141200.,
       141400., 142000., 143100., 141500., 140000., 139500., 138000.,
       136600., 1370

In [57]:
((siga+jongga)/2)*s[:,4]

array([4.1880573e+09, 4.1784666e+09, 4.2752617e+09, 4.2106035e+09,
       4.1304630e+09, 4.0764252e+09, 4.0195546e+09, 4.0668785e+09,
       4.2234949e+09, 4.1848556e+09, 4.2947241e+09, 4.5587461e+09,
       4.6025283e+09, 4.6025477e+09, 4.5924055e+09, 4.6972452e+09,
       4.8238961e+09, 5.0751012e+09, 5.0435799e+09, 4.9419028e+09,
       5.0965340e+09, 5.0894945e+09, 4.9698575e+09, 4.9034854e+09,
       5.0327624e+09, 4.9978373e+09, 5.0824161e+09, 5.0718152e+09,
       5.0506435e+09, 5.0470764e+09, 4.9873644e+09, 4.9626854e+09,
       4.9001313e+09, 4.9276370e+09, 5.0647613e+09, 5.1070853e+09,
       5.1676846e+09, 5.1783834e+09, 5.2150077e+09, 5.1541361e+09,
       5.2509983e+09, 5.2871373e+09, 5.1648097e+09, 5.0829476e+09,
       4.8757514e+09, 4.7893596e+09, 4.9661189e+09, 5.0650906e+09,
       5.1362796e+09, 5.2652365e+09, 5.2979789e+09, 5.1755034e+09,
       5.1113436e+09, 4.9876291e+09, 4.8653706e+09, 4.8792622e+09,
       4.8446080e+09, 4.7651118e+09, 4.9409654e+09, 4.9595295e