In [1]:
import numpy as np

In [3]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
arr.reshape(12)
arr.reshape(3*4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
arr.flatten() # 다차원 배열을 1차원 배열로 만들어줌

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
arr.ravel() #다차원 배열을 1차원 배열로 변환

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x=np.arange(3) #x는 1차원 배열
x

array([0, 1, 2])

In [10]:
x.reshape(1,3) #x는 2차원 배열 (행렬) 대괄호가 하나 더 있음 1행 3열짜리 배열


array([[0, 1, 2]])

In [11]:
x.reshape(3,1) #x는 2차원 3행 1열 짜리 배열

array([[0],
       [1],
       [2]])

In [12]:
x.reshape(1,3,1)

array([[[0],
        [1],
        [2]]])

In [13]:
x=np.arange(3)
x

array([0, 1, 2])

In [14]:
x[:,]

array([0, 1, 2])

In [26]:
x[:,np.newaxis].shape #2차원 3행 1열로 차원 추가

(3, 1)

In [32]:
arr=np.arange(12).reshape(3,4)
arr=arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
for i in arr:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [38]:
arr=arr.reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
for i in arr:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [41]:
for i in arr:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [44]:
arr=arr.reshape(2,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [49]:
for i in arr:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11


In [50]:
# 파이썬:리스트,튜플,딕셔너리,집합
# 넘파이: 배열(ndarray) :동일한 타입에 대한 자료가 저장
# 판다스:데이터프레임,시리즈
# 데이터 수집(크롤링,db) -> 전처리(넘파이,판다스)->분석(판다스)

In [65]:
a1=np.ones((3,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
a2=np.zeros((3,3))
a2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [67]:
np.hstack([a1,a2]) #행의 개수가 다를때 hstack()은 불가 hstack은 행으로 붙이는 함수이기 때문 (horizontal: 수평)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [68]:
np.vstack([a1,a2]) #vertical 열로 합쳐지는 함수 vstack() 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.dstack([a1,a2]) #깊이방향으로 더해지는 (depth:깊이) dstack()함수

array([[[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.]]])

In [70]:
a1=np.ones((3,4))
a2=np.zeros((3,4))

In [71]:
a1,a2

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [72]:
np.dstack([a1,a2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [74]:
np.dstack([a1,a2,a2]).shape #3,4 가 두개 합쳐지는 2,3,4가 아니라 3,4,2 로 합쳐짐 2개의 3*4배열 => 1개의 3*4*2배열이 됨

(3, 4, 3)

In [75]:
np.dstack([a1,a2,a2]) #뒤에 숫자가 붙으며 합쳐져 dstack()은 잘 사용하지 않으며,stack()을 주로 사용

array([[[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]]])

In [77]:
np.stack([a1,a2]) #2개 3*4=> 1개의 2*3*4 로 됨 숫자가 앞에 붙으면서 합쳐짐

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [79]:
np.stack([a1,a2]).shape  #axis(축)를 지정, 기본값 0이기 때문에 가장 왼쪽에 축이 지정되서 추가됨 3,4 앞에 2가 추가되어 2,3,4가됨

(2, 3, 4)

In [80]:
np.stack([a1,a2], axis=0) #위에 기본값형태

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [81]:
np.stack([a1,a2], axis=1)

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [82]:
np.stack([a1,a2], axis=1).shape #새로운 축이 중간에 추가

(3, 2, 4)

In [83]:
np.stack([a1,a2], axis=2) #axis (축)을 2로 지정하면 3,4,2가 됨
#두 행렬 3,4 를 stack함수로 연결할 때 axis 값에 따라 shape이 달라짐

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [84]:
a1=np.array([1,2,3])
a2=np.array([11,12,13])

In [85]:
np.hstack([a1,a2])

array([ 1,  2,  3, 11, 12, 13])

In [86]:
np.r_[a1,a2] #특별한 함수, 인덱서함수 ,r(row: 행)

array([ 1,  2,  3, 11, 12, 13])

In [87]:
np.c_[a1,a2] #c(column : 열 )

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [88]:
np.vstack([a1,a2])

array([[ 1,  2,  3],
       [11, 12, 13]])

In [90]:
#tile 함수: 동일한 배열을 반복해서 연결
arr=np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
np.tile(arr,3) #좌우 방향으로 3번 반복

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [96]:
np.tile(arr,(3,1)) #위아래로 3번 반복, 좌우방향으로 1번반복

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [97]:
np.tile(arr,(3,2)) #위아래로 3번 반복, 좌우방향으로 2번반복

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [99]:
arr1=np.array([0,0,0,1,1])
np.tile(arr1,(3,1))

array([[0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1]])

In [113]:
x=np.arange(3)
y=np.arange(5)

In [114]:
x,y=np.meshgrid(x,y)


In [115]:
[list(zip(x,y)) for x,y in zip(x,y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [116]:
arr1=np.array([1,2,3])
arr2=np.array([11,21,31])

In [117]:
np.concatenate([arr1,arr2])

array([ 1,  2,  3, 11, 21, 31])

In [118]:
arr=np.arange(6)
arr_f= [arr + i*10 for i in range(6)]
arr_f=np.array(arr_f)
print(arr_f)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [119]:
arr1=np.arange(6)
arr2=np.arange(0,51,10)

In [123]:
ar1,ar2=np.meshgrid(arr1,arr2)

In [124]:
ar1+ar2

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [125]:
x=np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [129]:
y=np.vstack(x)
np.meshgrid(x,y)

[array([[0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5]]),
 array([[0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5]])]

In [131]:
x+y*10

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [133]:
a=np.arange(1,5)
b=np.array([4,2,2,4])
a,b

(array([1, 2, 3, 4]), array([4, 2, 2, 4]))

In [134]:
a>=b

array([False,  True,  True,  True])

In [136]:
np.all(a>=b) #각 요소들을 일일이 비교하는게 아니라 ,배열의 모든 요소에 대해 조건만족하는지 모두 확인

False

In [137]:
#벡터(행렬)끼리 연산하려면 크기가 동일해야 함
#브로드캐스팅: 벡터(행렬)의 크기가 서로 다르더라도 연산이 가능하도록 크기를 동일하게 맞춰주는 작업
# 벡터         스칼라
# 1                        11
# 2                        12
# 3       +       10 =      13
# 4                       14
x=np.arange(1,5)

In [138]:
# 행렬(2) 벡터(1)-> 행렬(2)
# 012      10 10 10
# 123   +  11 11  11
# 234      12 12 12 
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [139]:
y=1 #스칼라였던 y=1이 [1,1,1,1,1] 벡터로 바뀐후 요소간 덧셈이 됨 (브로드캐스팅)

In [140]:
x+y

array([1, 2, 3, 4, 5])

In [146]:
y=np.ones_like(x)

In [144]:
x+y

array([1, 2, 3, 4, 5])

In [147]:
x=np.arange(5)

In [154]:
x=np.arange(3)
y=np.arange(5)
x,y=np.meshgrid(x,y)
x+y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [161]:
x = np.arange(3)
y=np.arange(5).reshape(5,1)
x+y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [164]:
np.vstack([range(7)[i:i+3] for i in range(5)])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])