In [2]:
# pandas
# 통계분석
# 데이터마이닝
# 시각화(matplotlib,tableau,seaborn,plotly,...)
# 머신러닝(scikit-learn)
# 딥러닝(tensorflow,keras,pytorch)-cnn,rnn,rl,yolo등


In [5]:
import numpy as np
np.random.seed(12345)


In [6]:
np.set_printoptions(precision=4)

In [9]:
#반올림(기본값 8자리로 설정),자릿수 지정

In [10]:
np.array([1.23456789])

array([1.2346])

In [12]:
np.set_printoptions(precision=8)

In [13]:
np.array([1.23456789])

array([1.23456789])

In [17]:
np.arange(10000) # 1000개까지 전체출력, 1000개 초과시 ...으로 표현 출력

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [21]:
np.set_printoptions(threshold=2000) #default 값이 1000개이지만 2000개까지 출력하도록 변경
np.set_printoptions(threshold=np.inf) #무한대까지 전체출력 np에서 무한대 = inf

In [22]:
np.arange(2001)

array([   0,    1,    2, ..., 1998, 1999, 2000])

In [39]:
data = [np.random.standard_normal() for i in range(7)] #표준 정규분포를 따르는 데이터값에서 임의로 데이터를 랜덤하게 뽑음 평균0 표준편차=1
data

[0.8864293405915888,
 -2.0016373096603974,
 -0.3718425371402544,
 1.6690253095248706,
 -0.4385697358355719,
 -0.5397414455216628,
 0.4769850104122995]

In [40]:
np.mean(data)

-0.04562162394701824

In [41]:
a=[1,2,3]
b=a # 동일한 메모리 주소값. a가 바뀌면 b도 바뀌어버림

In [42]:
a

[1, 2, 3]

In [43]:
b

[1, 2, 3]

In [44]:
a==b

True

In [45]:
c=a.copy() # c는 a 자체를 카피해서 저장해놓음
c

[1, 2, 3]

In [46]:
a.append(4)

In [47]:
a

[1, 2, 3, 4]

In [48]:
b

[1, 2, 3, 4]

In [49]:
c

[1, 2, 3]

In [50]:
c = """
This is a longer string that
spans multiple lines
"""

In [51]:
c.count("\n")

3

In [53]:
a = "this is a string"

In [54]:
b = a.replace("string", "longer string")
b

'this is a longer string'

In [55]:
a = 5.6
s = str(a)
print(s)

5.6


In [56]:
s = "12\\34"
print(s)

12\34


In [57]:
a = "this is the first half "
b = "and this is the second half"
a+b

'this is the first half and this is the second half'

In [58]:
template = "{0:.2f} {1:s} are worth US${2:d}" # 소수점 2자리 이하 실수가 0번 1번이 s=문자열 2번은 d=실수

In [59]:
template.format(88.46, "Argentine Pesos", 1) # 차례대로 0,1,2 자리에 들어감

'88.46 Argentine Pesos are worth US$1'

In [60]:
amount = 10
rate = 88.46
currency = "Pesos"
result = f"{amount} {currency} is worth US${amount / rate}" # f사용해서 문자,숫자 상관없이 포메팅가능

In [61]:
result

'10 Pesos is worth US$0.11304544426859599'

In [62]:
False or True

True

In [63]:
from datetime import datetime, date, time
dt = datetime(2024, 5, 21, 9, 45, 21)

In [64]:
dt

datetime.datetime(2024, 5, 21, 9, 45, 21)

In [65]:
dt.day

21

In [66]:
dt.minute

45

In [67]:
dt.date()

datetime.date(2024, 5, 21)

In [69]:
dt.time()

datetime.time(9, 45, 21)

In [70]:
states = ["   Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda",
          "south   carolina##", "West virginia?"]

import re



In [78]:
def clean_strings(strings):
    result=[]
    for value in strings:
        value=value.strip()
        value=re.sub("[!#?]","",value) #첫번째 패턴을 2번째 패턴으로 치환 value문자열에서
        value=value.title() #각 단어의 첫번째 문자가 대문자로 변경 두번째부터는 소문자로
        result.append(value)
    return result

In [79]:

clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [80]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [81]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [83]:
arr1.dtype

dtype('float64')

In [84]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [85]:
float_arr = arr.astype(np.float64) #astype = 데이터의 타입을 변환
float_arr

array([1., 2., 3., 4., 5.])

In [86]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [87]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [88]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [89]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
arr[5]

5

In [92]:
arr[5:8]

array([5, 6, 7])

In [93]:
arr[5:8] = 12

In [94]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [95]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [96]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [97]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [98]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [99]:
arr3d.shape

(2, 2, 3)

In [100]:
arr2d[2][2]

9

In [104]:
arr2d[:2][:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])

In [106]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [109]:
names[names=="Bob"]

array(['Bob', 'Bob'], dtype='<U4')

In [110]:
data[names=="Bob"] #순서가 똑같지만 배열이 다른 상태라면 불린참조로 참조가능

array([[4, 7],
       [0, 0]])

In [111]:
data[names=="Bob",1] # 특정조건을 만족하는 자료에서 1열에 해당하는 값을 출력

array([7, 0])

In [113]:
data[names=="Bob",1:] #1열부터 뒤에끝까지 모두 추출

array([[7],
       [0]])

In [114]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [115]:
names !="Bob"#not equal,!=

array([False,  True,  True, False,  True,  True,  True])

In [118]:
names == "Bob"
#!(names=="Bob")#문법오류
~(names=="Bob") # ~는 부정

array([False,  True,  True, False,  True,  True,  True])

In [119]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [120]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [121]:
data[names!="Bob"]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [122]:
data[(names =='Bob') | (names =='Will')] # |: or (또는) , &: and(그리고)


array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [124]:
data<0 #배열의 모든 요소와 비교

array([[False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True,  True],
       [False, False]])

In [126]:
data[data<0] # 결과가 2차원array에서 1차원 array가 됨

array([ -5, -12,  -4])

In [127]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [128]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [131]:
data[names!="Joe"]=7
data

array([[  7,   7],
       [  0,   2],
       [  7,   7],
       [  7,   7],
       [  7,   7],
       [-12,  -4],
       [  3,   4]])

In [132]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [133]:
arr[3:5]

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [134]:
arr[[4,3,6,0]] #여러개의 행을 내가 원하는 순서대로 추출하고싶을때 대괄호 하나 안에 행을 여러개 추출

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [6., 6., 6., 6.],
       [0., 0., 0., 0.]])

In [137]:
arr[7]

array([7., 7., 7., 7.])

In [138]:
arr[-1]

array([7., 7., 7., 7.])

In [139]:
arr[[-1,-3,-5]]

array([[7., 7., 7., 7.],
       [5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [144]:
arr[5:2:-1]

array([[5., 5., 5., 5.],
       [4., 4., 4., 4.],
       [3., 3., 3., 3.]])

In [167]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [168]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [172]:
#배열명 [[행번호],[열번호]] => (행번호,열번호) 이런식으로 쌍을 이뤄서 쌍에대한 요소값을 추출해버림
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [173]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [175]:
arr[:,[0,3,1,2]][[1,5,7,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [176]:
arr[[1,5,7,2],[0,3,1,2]]=0

In [177]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [178]:
arr[[1,5,7,2]]=0
arr

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 0,  0,  0,  0],
       [24, 25, 26, 27],
       [ 0,  0,  0,  0]])

In [182]:
arr=np.arange(15).reshape((3,5)) #3행 5열
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [183]:
arr.T #5행 3열 

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [189]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [188]:
arr.T

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [187]:
arr@arr.T # 5,3 @ 3,5 =5,5 행렬의 곱


array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

In [190]:
arr.T @ arr #3,5 @ 5,3= 3,3

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [192]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
np.sqrt(arr) #제곱근

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [194]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [196]:
x=[]
for i in range(len(xarr)):
    if cond[i]==True:
        x.append(xarr[i])
    else:
        x.append(yarr[i])

In [202]:
np.array(x)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [201]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [203]:
[(x,y,z) for x,y,z  in zip(xarr, yarr, cond)]

[(1.1, 2.1, True),
 (1.2, 2.2, False),
 (1.3, 2.3, True),
 (1.4, 2.4, True),
 (1.5, 2.5, False)]

In [204]:
[x if z else y for x,y,z  in zip(xarr, yarr, cond)]

[1.1, 2.2, 1.3, 1.4, 2.5]

In [205]:
#np.where(조건, 참, 거짓) 참이면 2째 값 참조 거짓이면 세번째 값 참조
np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [208]:
arr=np.random.standard_normal((4,4))
arr>0

array([[ True, False, False,  True],
       [ True, False,  True, False],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [209]:
np.where(arr>0,1,-1)

array([[ 1, -1, -1,  1],
       [ 1, -1,  1, -1],
       [ 1,  1,  1, -1],
       [-1, -1, -1, -1]])

In [210]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [214]:
np.where(arr%3==0,3,arr)

array([[ 3,  1,  2,  3],
       [ 4,  5,  3,  7],
       [ 8,  3, 10, 11]])

In [217]:
np.mean(arr,axis=1) #행단위

array([1.5, 5.5, 9.5])

In [218]:
np.mean(arr,axis=0) #열단위

array([4., 5., 6., 7.])

In [219]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum() # 누적 합 1차원 구조 array로 나옴

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [220]:
arr.sum()

28

In [222]:
arr = np.random.standard_normal(100)
arr

array([ 2.22465959e+00, -6.79400410e-01,  7.27368782e-01, -8.68730734e-01,
       -1.21385091e+00, -4.70630931e-01, -9.19241697e-01, -8.38826689e-01,
        4.35155305e-01, -5.57804717e-01, -5.67454871e-01, -3.72641553e-01,
       -9.26556901e-01,  1.75510839e+00,  1.20980999e+00,  1.27002473e+00,
       -9.74378127e-01, -6.34709255e-01, -3.95700752e-01, -2.89435900e-01,
       -7.34297072e-01, -7.28504679e-01,  8.38775073e-01,  2.66893213e-01,
        7.21194339e-01,  9.10982642e-01, -1.02090261e+00, -1.41341604e+00,
        1.29660784e+00,  2.52275209e-01,  1.12748110e+00, -5.68363447e-01,
        3.09362168e-01, -5.77385473e-01, -1.16863407e+00, -8.25019972e-01,
       -2.64440949e+00, -1.52985803e-01, -7.51921003e-01, -1.32609252e-01,
        1.45729970e+00,  6.09511845e-01, -4.93779257e-01,  1.23997988e+00,
       -1.35722140e-01,  1.43004181e+00, -8.46852451e-01,  6.03282130e-01,
        1.26357226e+00, -2.55490556e-01, -4.45688380e-01,  4.68366681e-01,
       -9.61603924e-01, -

In [224]:
(arr>0).sum() #True:1, False:0 즉 양수의 개수가 41개

41

In [225]:
(arr<=0).sum()

59

In [226]:
bools=np.array([False,False,True,False])
bools.sum()

1

In [227]:
bools.any()

True

In [228]:
bools.all()

False

In [229]:
arr2 = np.array([5, -10, 7, 1, 0, -3])

In [230]:
np.sort(arr2)

array([-10,  -3,   0,   1,   5,   7])

In [231]:
arr2 # 정렬한것이 적용되지 않음

array([  5, -10,   7,   1,   0,  -3])

In [232]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names) #중복을 제거

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [233]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [235]:
set(ints)
set(names)

{'Bob', 'Joe', 'Will'}

In [237]:
np.save("data",arr)#arr에 저장된 데이터가 binary 형태로 data.npy에 저장됨

In [238]:
np.load("data.npy")

array([ 2.22465959e+00, -6.79400410e-01,  7.27368782e-01, -8.68730734e-01,
       -1.21385091e+00, -4.70630931e-01, -9.19241697e-01, -8.38826689e-01,
        4.35155305e-01, -5.57804717e-01, -5.67454871e-01, -3.72641553e-01,
       -9.26556901e-01,  1.75510839e+00,  1.20980999e+00,  1.27002473e+00,
       -9.74378127e-01, -6.34709255e-01, -3.95700752e-01, -2.89435900e-01,
       -7.34297072e-01, -7.28504679e-01,  8.38775073e-01,  2.66893213e-01,
        7.21194339e-01,  9.10982642e-01, -1.02090261e+00, -1.41341604e+00,
        1.29660784e+00,  2.52275209e-01,  1.12748110e+00, -5.68363447e-01,
        3.09362168e-01, -5.77385473e-01, -1.16863407e+00, -8.25019972e-01,
       -2.64440949e+00, -1.52985803e-01, -7.51921003e-01, -1.32609252e-01,
        1.45729970e+00,  6.09511845e-01, -4.93779257e-01,  1.23997988e+00,
       -1.35722140e-01,  1.43004181e+00, -8.46852451e-01,  6.03282130e-01,
        1.26357226e+00, -2.55490556e-01, -4.45688380e-01,  4.68366681e-01,
       -9.61603924e-01, -

In [239]:
brr=np.arange(10)
brr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [240]:
np.savez("data2.npz",a=arr,b=brr) #여러개의 array를 zip으로 묶어 저장

In [244]:
x=np.load("data2.npz")
x['a']

array([ 2.22465959e+00, -6.79400410e-01,  7.27368782e-01, -8.68730734e-01,
       -1.21385091e+00, -4.70630931e-01, -9.19241697e-01, -8.38826689e-01,
        4.35155305e-01, -5.57804717e-01, -5.67454871e-01, -3.72641553e-01,
       -9.26556901e-01,  1.75510839e+00,  1.20980999e+00,  1.27002473e+00,
       -9.74378127e-01, -6.34709255e-01, -3.95700752e-01, -2.89435900e-01,
       -7.34297072e-01, -7.28504679e-01,  8.38775073e-01,  2.66893213e-01,
        7.21194339e-01,  9.10982642e-01, -1.02090261e+00, -1.41341604e+00,
        1.29660784e+00,  2.52275209e-01,  1.12748110e+00, -5.68363447e-01,
        3.09362168e-01, -5.77385473e-01, -1.16863407e+00, -8.25019972e-01,
       -2.64440949e+00, -1.52985803e-01, -7.51921003e-01, -1.32609252e-01,
        1.45729970e+00,  6.09511845e-01, -4.93779257e-01,  1.23997988e+00,
       -1.35722140e-01,  1.43004181e+00, -8.46852451e-01,  6.03282130e-01,
        1.26357226e+00, -2.55490556e-01, -4.45688380e-01,  4.68366681e-01,
       -9.61603924e-01, -

In [245]:
x['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [246]:
brr.max()

9

In [247]:
brr.min()

0

In [248]:
brr.mean()

4.5

In [250]:
# 시계열 (time series) ->Series (pandas에서 시계열 데이터를 분석할때 쓰는 자료구조,클래스)
# 표 (table) -> DataFrame (pandas에서 표 데이터를 분석할때 쓰는 자료구조,클래스)
#분석 데이터유형이 대부분 두가지중 하나이므로 Series나 DataFrame 형식으로 데이터 분석을 함. pandas에서 Series와 DataFrame클래스를 제공

In [251]:
import pandas as pd

In [252]:
#python:list,set,dict,tuple
#numpy:n-dimensional array

#pandas : Series, DataFrame

#Series: numpy 1차원 array와 매우 유사함. 차이점은 Series는 index가 있음.
# 시리즈 = 데이터(1차원 구조) + 인덱스
# DataFrame = numpy의 2차원 array와 매우 유사함 . 차이점은 DataFrame에는 행 index, 열 index가 있음.
# DataFrame = 데이터(2차원) + 행 index + 열 index


In [255]:
li=[1,2,3]
li
np.array(li)

array([1, 2, 3])

In [256]:
s=pd.Series([10,20,30,40]) #행 인덱스가 자동 부여(0~)
s


0    10
1    20
2    30
3    40
dtype: int64

In [257]:
s2=pd.Series([10,20,30,40],index=['월','화','수','목']) #행인덱스 직접 부여. 인덱스는 문자 숫자 다 가능 한글 영어 다 가능
#pd.Series(데이터,인덱스) 일반적으로 인덱스가 시간의 흐름을 나타냄 시계열 데이터가 아닌 데이터도 Series자료구조로 나타낼 수 있긴 함.
s2

월    10
화    20
수    30
목    40
dtype: int64

In [259]:
s3=pd.Series([90,70,60,80],index=['홍길동','임꺽정','세종','인조']) #몸무게
s3

홍길동    90
임꺽정    70
세종     60
인조     80
dtype: int64

In [260]:
pd.Series(list(range(10,15)))

0    10
1    11
2    12
3    13
4    14
dtype: int64

In [262]:
s3

홍길동    90
임꺽정    70
세종     60
인조     80
dtype: int64

In [263]:
s3.index

Index(['홍길동', '임꺽정', '세종', '인조'], dtype='object')

In [264]:
s3.values

array([90, 70, 60, 80], dtype=int64)

In [265]:
s3.index.name="인물"

In [266]:
s3.name="몸무게"

In [267]:
s3

인물
홍길동    90
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [268]:
s3/10 # s3에 해당하는 모든데이터들에 대해 모두 연산

인물
홍길동    9.0
임꺽정    7.0
세종     6.0
인조     8.0
Name: 몸무게, dtype: float64

In [269]:
s3

인물
홍길동    90
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [272]:
s3['세종'] #index는 변수가 아니므로 따옴표로 묶어줘야함 


60

In [273]:
s3[2] #

C:\Users\master\AppData\Local\Temp\ipykernel_2428\3055280449.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s3[2]


60

In [274]:
s3.iloc[2] #iloc는 속성

60

In [275]:
s3['임꺽정']

70

In [277]:
s3[['임꺽정','세종']] #array처럼 대괄호를 하나 더 써서 행 인덱스를 여러개 추출

인물
임꺽정    70
세종     60
Name: 몸무게, dtype: int64

In [278]:
s3.iloc[[1,2]]

인물
임꺽정    70
세종     60
Name: 몸무게, dtype: int64

In [279]:
s3

인물
홍길동    90
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [280]:
s3>70

인물
홍길동     True
임꺽정    False
세종     False
인조      True
Name: 몸무게, dtype: bool

In [281]:
s3[s3>70]

인물
홍길동    90
인조     80
Name: 몸무게, dtype: int64

In [285]:

s3[(s3>=60) & (s3<=80)]

인물
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [286]:
s3.iloc[1:3]

인물
임꺽정    70
세종     60
Name: 몸무게, dtype: int64

In [287]:
s3['임꺽정':'인조'] # 인조 포함

인물
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [51]:
r=[1,0]
x=np.ones(20)*np.random.choice(r,size=20)
list(x).count(1)

10

In [137]:
r=[1,0]
x=np.random.choice(r,size=10000)
x.mean()

0.5015

In [72]:
arr=np.random.choice(100,size=20).reshape((4,5))
np.max(arr)

97

In [74]:
np.sum(arr,axis=1)

array([244, 181, 380, 301])

In [75]:
arr

array([[34, 44, 35, 58, 73],
       [ 9,  8, 28, 57, 79],
       [97, 44, 64, 82, 93],
       [73, 42, 77, 82, 27]])

In [76]:
np.sum(arr,axis=0)

array([213, 138, 204, 279, 272])

In [77]:
np.max(arr,axis=1)

array([73, 79, 97, 82])

In [78]:
np.mean(arr,axis=0)

array([53.25, 34.5 , 51.  , 69.75, 68.  ])

In [79]:
np.min(arr,axis=0)

array([ 9,  8, 28, 57, 27])

In [83]:
import pandas as pd
arr=pd.Series([1000,300,200,100],index=['서울','부산','인천','광주'])

In [84]:
arr['광주']

100

In [87]:
data=pd.Series(list(range(10,60,10)),index=['가','나','다','라','마'])

In [88]:
data

가    10
나    20
다    30
라    40
마    50
dtype: int64

In [90]:
data[['나','라']]
data.iloc[[1,3]]

나    20
라    40
dtype: int64

In [99]:
np.random.seed(20)
sample2 = pd.Series(np.random.randint(100, 200, size=15))
sample2

0     199
1     190
2     115
3     195
4     128
5     190
6     109
7     120
8     175
9     122
10    171
11    134
12    196
13    140
14    185
dtype: int32

In [100]:
sample2[sample2>160]

0     199
1     190
3     195
5     190
8     175
10    171
12    196
14    185
dtype: int32

In [107]:
sample2[(170>=sample2) & (sample2>=130)]

11    134
13    140
dtype: int32

In [108]:
pd.Series(['apple','NaN','banana','kiwi','gubong'],index=['가','나','다','라','마'],dtype='object')

가     apple
나       NaN
다    banana
라      kiwi
마    gubong
dtype: object

In [132]:
import random
x=range(1,21)
arr=list(np.random.choice(x,size=10,replace=False))
# if a in arr:
#     print(arr.index[a])
# else:
#     print(-1)
print(arr)
a=int(input("숫자"))
for i in range(len(arr)):
    if a==arr[i]:
        print(i)
        break
    elif i==len(arr)-1:
        print(-1)

[10, 4, 15, 18, 9, 5, 2, 16, 13, 11]


숫자 1


-1
