In [54]:
import numpy as np


In [29]:
#시드(seed)를 이용하여 난수 발생 

In [70]:
np.random.rand()

0.1087070451683314

In [71]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [72]:
np.random.seed(20240510) #-> 동일한 난수 시드를 설정 하면 동일한 랜덤값이 나옴

In [73]:
np.random.rand()

0.24432338459661196

In [74]:
np.random.rand(10)

array([0.63551756, 0.67221731, 0.8370985 , 0.3230404 , 0.66728613,
       0.99852928, 0.95145872, 0.36059922, 0.68687786, 0.21542222])

In [75]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.random.shuffle(x)
x

array([9, 3, 4, 6, 5, 0, 7, 1, 2, 8])

In [77]:
np.sort(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
#choice: 표본 추출 함수


In [90]:
x=np.arange(11,15)
x

array([11, 12, 13, 14])

In [92]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
x=np.arange(11,15)
x

array([11, 12, 13, 14])

In [121]:
np.random.choice(x) #replace=false 비복원추출 True 복원추출 replacement :다시 넣어서 추출하는것 default  값은 True
#p= 가중값 부여 특정 요소 추출할때 가중값을 매김

0

In [8]:
np.random.choice(5,3,p=[0.1,0,0.3,0.6,0]) #0부터 4까지중에 3개를 뽑는데 p로 확률을 조절 0 1 2 3 4 가 각각 0.1 /0 /0.3/0.3/0 확률 로 뽑히게 조절 replace=True 기본값으로 설정되있기때문에 복원추출 방식 

array([2, 2, 3])

In [5]:
arr=np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])

In [6]:
arr

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [9]:
np.random.rand() # 0~1사이 난수  0포함 1미만 0<=난수 <1

0.1574624213590904

In [10]:
np.random.randn() # 표준정규분포(평균:0 ,표준편차: 1)

1.5511233503006476

In [12]:
np.random.randint(5) #균등분포 (동일한 확률), 정수난수 

0

In [13]:
np.random.rand(15) #()안에 숫자를 넣으면 해당 숫자개수만큼 생성

array([0.37863347, 0.93802561, 0.44490132, 0.44466642, 0.95841598,
       0.65311682, 0.7572166 , 0.4287035 , 0.13458341, 0.99475483,
       0.90057974, 0.76284146, 0.66673556, 0.98118347, 0.28929281])

In [14]:
np.random.rand(3,5) #이렇게 주면 3*5 형태로 reshape 해서 줌

array([[0.15481037, 0.49144566, 0.13567962, 0.15520901, 0.29473749],
       [0.9261752 , 0.44478826, 0.83595405, 0.33466912, 0.65362527],
       [0.34289631, 0.88778388, 0.4814177 , 0.75075054, 0.96658099]])

In [15]:
np.random.randn(10) 

array([ 0.08161611, -0.02417888, -1.54652036,  0.92817186, -1.06328762,
       -0.90604684, -0.04755961, -0.4877113 ,  0.59202769,  1.46627689])

In [120]:
np.mean(np.random.randn(10)) # randn 함수는 평균값이 0에 가까운 값이 나옴 

-0.021941197922964607

In [118]:
np.std(np.random.randn(10)) # randn 함수는 또한 표준편차는 1에 수렴하게 됨 즉 평균이 0에 가까우면서 표준편차는 1

0.8196023141880632

In [119]:
np.random.randint(3,7,size=10) # 0~2사이 랜덤값 추출 (3,7)로 주면 3부터 7미만까지범위에서 추출  즉 3부터 6까지 범위에서 추출 size=a로 a개의 데이터 추출가능
# size=(2,5) 이런식으로 2*5행렬로 추출도 가능

array([4, 3, 4, 6, 6, 5, 3, 5, 6, 4])

In [25]:
np.random.randint(3,7,size=(2,4))

array([[6, 3, 6, 5],
       [6, 3, 3, 5]])

In [27]:
data=np.random.randint(5,11,size=10)
data

array([10,  9,  6,  8,  9,  7,  9,  8,  6,  6])

In [28]:
np.unique(data) #중복값들은 제외하고 유일한 수들만 나옴

array([ 6,  7,  8,  9, 10])

In [117]:
np.unique(data, return_counts=True) #0번배열에는 유일한 수들의 배열 1번배열에는 각각의 빈도수의 배열이 나옴
#난수범위중에서 추출되지 않은 수들에 대한 정보는 확인을 불가 ex) 지금 상황에서 5에대한 정보를 알 수 없음

(array([ 6,  7,  8,  9, 10]), array([3, 1, 2, 3, 1], dtype=int64))

In [34]:

np.unique(data, return_counts=True)[0]

array([ 6,  7,  8,  9, 10])

In [35]:
np.unique(data, return_counts=True)[1]

array([3, 1, 2, 3, 1], dtype=int64)

In [116]:
np.bincount(data,minlength=12) #minlength: 0부터 설정된값 미만까지 수를 범위로 설정하여 빈도수 조사
np.bincount(data) # 그냥 쓰면 데이터가 나온 최댓값까지만 빈도수 조사 

array([0, 0, 0, 0, 0, 0, 3, 1, 2, 3, 1], dtype=int64)

In [37]:
data

array([10,  9,  6,  8,  9,  7,  9,  8,  6,  6])

In [87]:
a=np.arange(1,46)
res=[]
for x in range(5):
    res.append(np.random.choice(a,size=(1,6),replace=False))
res

[array([[ 6, 35, 20,  3,  1, 44]]),
 array([[27, 29, 45, 17, 31, 37]]),
 array([[16, 36, 23,  1, 26, 29]]),
 array([[27,  2, 25,  4, 33, 18]]),
 array([[19, 10, 32, 24, 21, 18]])]

In [115]:
a=np.array([0,1])
x=np.random.choice(a,size=10)

In [113]:
#1번
a=np.arange(1,46)
res=[]
for x in range(5):
    res.append(np.random.choice(a,size=(1,6),replace=False))
res


[array([[ 5, 22, 45, 20, 21, 34]]),
 array([[42, 37,  6,  3, 27,  2]]),
 array([[28, 32, 26, 45, 29, 19]]),
 array([[42, 28, 22, 14,  7,  2]]),
 array([[28, 12, 43, 37, 20, 40]])]

In [112]:
#2번
a=np.array([0,1])
x=np.random.choice(a,size=10)
for res in x:
    if res==0:
        print("앞면")
    else:
        print("뒷면")

뒷면
앞면
앞면
앞면
앞면
앞면
앞면
앞면
앞면
앞면


In [124]:
#3번
a=np.arange(1,7)
np.mean(np.random.choice(a,size=100000000))

3.50049844

In [127]:
import requests
import json

city="Seoul"
apikey='5450febaf93eb267f65db4dad959f82e'
lang= "Kr"
units='metric'
api =f"""http://api.openweathermap.org/data/2.5/
weather?q={city}&appid={apikey}&lang={lang}&units={units}"""

result = requests.get(api)
data = json.loads(result.text)
print(data)


{'cod': '404', 'message': 'Internal error'}


In [130]:
list = [1,3,0,4,2]
cnt = 0
index = 1

In [168]:
list = [1,3,0,4,2]
cnt = 0
index = 1
while index != 0:
    index=list[index]
    cnt = cnt + 1
print(cnt)

4


In [136]:
arr = [1,2,6,5,4,2]
dat = [0 for _ in range(len(arr) + 1)] 

for i in range((len(arr))): 
    dat[arr[i]] = 1 

for i in range(len(dat)):
    if dat[i] == 0:
        continue
    print(i, end = " ")

1 2 4 5 6 

In [140]:
str = "ABKRNW"
idx = [1, 3, 1, 3, 2]
result = ""

for i in range(len(idx)):
    result += str[idx[i]]

print(result)

BRBRK


In [143]:
arr = [[0 for _ in range(3)] for _ in range(3)]
arr
t = 1

for i in range(2,-1,-1): 2 1 0
    for j in range(0,3): 0 1 2
        arr[j][i] = t
        t = t + 1

# for i in range(0,3): 0 1 2
#     print(arr[i][i], end=" ")

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [149]:
# 다음 코드를 실행한 결과로 출력되는 값은?
arr = [[1, 1, 0, 1], [0, 1, 1, 0], [1, 1, 1, 0], [1, 1, 1, 1]]
cnt = 0 #7
1101 0110
for i in range(1,3): 1 2
    for j in range(2,4): 2 3
        if(arr[i][j] == 1):
            cnt = cnt + 1
    for j in range(0, 3): 012
        if (arr[i][j] == 1):
            cnt = cnt + 1
print(cnt) 

7


In [153]:
def meet(index):
    return (index * 3 + 11 ) % 10

0 0 0 1 1 1 0 0 0 0
dat = [0 for _ in range(10)]
dat
old = -1
start = 1
while True:
    start = meet(start) # 3
    if(dat[start] == 1):
        break
    dat[start] = 1

    if(old == start):
        break

print(start)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [154]:

arr = [1, 2, 3, 1, 2, 3, 9, 6, 5]
brr = [4, 3, 5, 2, 3, 1, 9]
dat = [0 for _ in range(10)]

for i in range(len(arr)): 
    dat[arr[i]] = 1

for i in range(len(brr)):
    dat[brr[i]] = 1

cnt = 0

for i in range(10): 0 9
    cnt += dat[i]

print(cnt) 

7


In [155]:
matrix = [[i for i in range(j*10, (j+1)*10)] for j in range(10)]

dr = [1, -1, 0, 0]
dc = [0, 0, -1, 1]

r, c = 5, 5

print(f'현재: {matrix[r][c]}')

for idx in range(4):
    nr = r + dr[idx]
    nc = c + dc[idx]

print(matrix[nr][nc])

현재: 55
56


In [167]:
matrix = [[i for i in range(j*10, (j+1)*10)] for j in range(10)]
matrix


dr = [1, -1, 0, 0]
dc = [0, 0, -1, 1]

r, c = 5, 5

print(f'현재: {matrix[r][c]}')

for idx in range(4):
    nr = r + dr[idx]
    nc = c + dc[idx]

    print(matrix[nr][nc])

현재: 55
65
45
54
56
